[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sustainability-framework"
version = "0.0.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ipynb>=0.5.1",
    "pandas>=3.0.1",
    "pip>=26.0.1",
    "pyarrow>=23.0.0",
    "scikit-learn>=1.3.2",
    "fastapi>=0.95.0",
    "uvicorn>=0.23.0",
]

[project.scripts]
start-api = "sustainability_framework.cli:main"
start-ml-api = "sustainability_framework.cli:start_ml_api"

[tool.setuptools.packages.find]
where = ["."]
include = ["sustainability_framework*"]
